version: "3"

services:
  redis:
    image: redis:alpine
    hostname: redis
    ports:
      - "6379:6379"
    expose:
      - '6379'
    networks:
      - webnet

  pg:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - webnet

  app:
    build: .
    command: npm run dev
    depends_on:
      - redis
    env_file: ./.env
    ports:
      - ${PORT}:${PORT}
    restart: "always"
    volumes: 
      - .:/usr/app
    networks:
      - webnet

networks:
  webnet: